arch: trans_enc #'trans_enc', 'trans_dec', 'gru'
emb_trans_dec: False
layers: 8
latent_dim: 512
ff_size: 1024
num_heads: 4

cond_mask_prob: 0
lambda_rcxyz: 1 #https://github.com/GuyTevet/motion-diffusion-model/issues/19
lambda_vel: 1
lambda_fc: 1
unconstrained: false 